//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.05 at 10:02:16 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kit.edu/cockpit/valuationserver/rest/messages", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.kit.cockpit.valuationserver.rest.messages;
